package:
  name: python3
  version: 3.11.6
  epoch: 0
  description: A high-level scripting language
  copyright:
    - paths: ["*"]
      license: PSF-2.0

environment:
  contents:
    repositories: [https://dl-cdn.alpinelinux.org/alpine/edge/main]
    packages:
      - busybox
      - dash
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.python.org/ftp/python/3.11.6/Python-3.11.6.tgz
      expected-sha256: c049bf317e877cbf9fce8c3af902436774ecef5249a29d10984ca3a37f7f4736
  - name: Force use of system libraries
    runs: |
      rm -rf Modules/expat \
        Modules/_ctypes/darwin* \
        Modules/_ctypes/libffi*
  - name: Configure
    runs: |
      ./configure \
        --host=$(uname -m)-pc-linux-gnu \
        --build=$(uname -m)-pc-linux-gnu \
        --target=$(uname -m)-pc-linux-gnu \
        --prefix=/usr \
        --enable-ipv6 \
        --enable-loadable-sqlite-extensions \
        --enable-optimizations \
        --enable-shared \
        --with-lto \
        --with-computed-gotos \
        --with-dbmliborder=gdbm:ndbm \
        --with-system-expat \
        --with-system-ffi \
        --with-system-libmpdec \
        --without-ensurepip
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: "python3-doc"
    description: "python3 documentation"
    pipeline:
      - uses: split/manpages

  - name: "python3-dev"
    description: "python3 development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/include/python3.11
          mv "${{targets.subpkgdir}}"/usr/include/python3.11/pyconfig.h "${{targets.destdir}}"/usr/include/python3.11
