on: {push: {branches: [main]}, schedule: [{cron: '1 13 * * *'}], workflow_dispatch: {}}
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {id-token: write, packages: write, contents: read}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - {python-release: '3.10'}
          - {python-release: '3.11'}
    concurrency: 'python3-alpine-${{ matrix.python-release }}'
    steps:
      - uses: actions/checkout@v3
      - run: sudo mkdir -p /work
      - uses: chainguard-dev/actions/melange-build@main
        with:
          config: melange-${{ matrix.python-release }}.yaml
          signing-key-path: /work/melange.rsa
          repository-path: /work/packages
          empty-workspace: false
          sign-with-temporary-key: true
      - name: Create temp copy of /work directory (used in next step)
        shell: bash
        run: |
          rm -rf .apko-automount && cp -r /work .apko-automount
      - uses: chainguard-images/actions/apko-snapshot@main
        with:
          config: apko.yaml
          base-tag: ghcr.io/infrabits/python3-alpine-${{ matrix.python-release }}
          keyring-append: /work/melange.rsa.pub
          automount-src: .apko-automount
          automount-dest: /work
