on: {push: {branches: [main]}, schedule: [{cron: '1 13 * * *'}], workflow_dispatch: {}}
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {id-token: write, packages: write, contents: read}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - {python-release: '3.10'}
          - {python-release: '3.11'}
    concurrency: 'python3-alpine-${{ matrix.python-release }}'
    steps:
      - uses: actions/checkout@v3
      - uses: chainguard-dev/actions/melange-build@main
        with:
          config: melange-python3.yaml
          sign-with-temporary-key: true
          empty-workspace: true
        if: matrix.python-release == '3.11'
      - run: find /github/workspace/
      - uses: chainguard-images/actions/apko-snapshot@main
        with:
          config: apko-${{ matrix.python-release }}.yaml
          base-tag: ghcr.io/infrabits/python3-alpine-${{ matrix.python-release }}
          keyring-append: /github/workspace/melange.rsa.pub
        if: matrix.python-release == '3.11'
      - uses: chainguard-images/actions/apko-snapshot@main
        with:
          config: apko-${{ matrix.python-release }}.yaml
          base-tag: ghcr.io/infrabits/python3-alpine-${{ matrix.python-release }}
        if: matrix.python-release != '3.11'
